### ISSUE TITLE
duty cycle calculation incorrect

### ISSUE THREAD

**Issue by Karateschnitzel** [timreyes/dutyCycle#1]
i tried out this extension and might have found a bug.
I would expect the duty cycle to be around 72%, as shown in the top left corner.

I'm using Logic 2 Release 2.3.13 with a saleae Logic Pro 8

![20201106 09_27_28_duty_cycle_extension](https://user-images.githubusercontent.com/17978084/98344108-0da02a80-2013-11eb-9c43-822e70f45fb8.png)

**Comment by timreyes** [comment]
Thanks for reporting this! Someone reported something similar in the past, but unfortunately I wasn't able to reproduce it at the time. Would you mind sharing your capture file (.sal format)?

**Comment by Karateschnitzel** [comment]
No problem 
[DC_Bug_trimmed.zip](https://github.com/timreyes/dutyCycle/files/5509370/DC_Bug_trimmed.zip)

**Comment by timreyes** [comment]
Thanks for sending that over. That's strange. I wasn't able to reproduce the issue. I opened your capture file as-is and the duty cycle looks correct (looks like you already had a measurement box in there).
<img width="1196" alt="Screen Shot 2020-11-09 at 5 03 42 PM" src="https://user-images.githubusercontent.com/27969866/98601865-41927e80-22a5-11eb-8064-205f04abc439.png">

- For the capture file you sent me, is your Duty Cycle measurement showing something different?
- Is the duty cycle calculation always incorrect at ~50%? Or just at certain spots?

Someone actually reported similar behavior in the past, which I was not able to reproduce on my end. I don't doubt you're running in the same thing. It was just odd that I couldn't reproduce it.

**Comment by Karateschnitzel** [comment]
- In the file I sent to you Duty would be 50.074 %. All other values of that measurement are the same.
- In a quick test with 2 different duties I measured 54.76% as 50.016 % and 69,81% as 50.066%.
So, yes it's always around 50%. It doesn't mather if the measurement were taken at falling or rising edge first.

**Comment by timreyes** [comment]
That's definitely strange that it shows up correctly on my end. This is something that another user reported to me too. I'll review this with the team here.

**Comment by Karateschnitzel** [comment]
I did a little debugging in the example I sent:
- self.total_pulse_length_of_first_type is 5.009ms 
- self.total_pulse_length_of_second_type is 5.024ms
- self.first_pulse_length is 9.268µs 
- self.current_pulse_length is 24.132µs
The first two values are obviously wrong. The only place were this can go wrong is at the += operator.
Maybe None + saleae.data.timing.GraphTimeDelta is giving wrong results here.

Hope this helps

**Comment by Karateschnitzel** [comment]
I could solve the problem by replacing
https://github.com/timreyes/dutyCycle/blob/master/dutyCycle.py#L51-L54
with
```
if((self.total_pulse_length_of_second_type == None) and (self.total_pulse_length_of_first_type == None)):
    self.total_pulse_length_of_second_type = self.current_pulse_length
    self.total_pulse_length_of_first_type = self.first_pulse_length
else:
    self.total_pulse_length_of_second_type = self.total_pulse_length_of_second_type + self.current_pulse_length
    # Wait until entire period is complete before tallying up the first pulse length
    self.total_pulse_length_of_first_type = self.total_pulse_length_of_first_type + self.first_pulse_length
```
Maybe you find a prettier way to solve it

**Comment by timreyes** [comment]
Thanks for the suggestion! I'm going to run some tests with the software team here to confirm if this was in fact the issue.

**Comment by FlYnN91** [comment]
I  am seeing the same issue. I am pretty sure my pulses are not 49%

![image](https://user-images.githubusercontent.com/774118/103779064-1c16bc80-502b-11eb-8c2e-01a4c53ea674.png)

**Comment by timreyes** [comment]
@FlYnN91 I just updated the extension in the marketplace. You can update it from the Logic 2 App (image below). Hope that solves it.
![Screen Shot 2021-01-06 at 11 43 11 PM](https://user-images.githubusercontent.com/27969866/103855851-23fd4d80-5079-11eb-9360-caf015e84456.png)

@Karateschnitzel Thanks again for suggesting the fix!

**Comment by Karateschnitzel** [comment]
I'm glad I could help. At least for me the update worked.
 
I found another way to solve the problem, which might be more readable.
At [line19 to 20](https://github.com/timreyes/dutyCycle/blob/master/dutyCycle.py#L19-L20) i replaced 

```
self.total_pulse_length_of_first_type =None 
self.total_pulse_length_of_second_type =None
```
with

```
self.total_pulse_length_of_first_type = GraphTimeDelta(0)
self.total_pulse_length_of_second_type = GraphTimeDelta(0)
```

**Comment by timreyes** [comment]
Sounds good. I'll keep that in mind in case I update this further, or add more features in the future.
